### ISSUE TITLE
TypeError using si_format

### ISSUE THREAD

**Issue by wreiner** [cfobel/si-prefix#1]
I get the the following error when using _si_format_ with _Python 3.5.1_:

```
Traceback (most recent call last):
  File "./x.py", line 8, in <module>
    print("%s s" % (si_format(1/50, precision=2)))
  File "/home/wreiner/coden/python/pwmcalc/si_prefix/__init__.py", line 115, in si_format
    return '%s%s' % (value_str, prefix(expof10))
  File "/home/wreiner/coden/python/pwmcalc/si_prefix/__init__.py", line 67, in prefix
    return prefix[si_level + prefix_levels]
TypeError: string indices must be integers
```

This occurs because the function _prefix_ uses floats in

```
return prefix[si_level + prefix_levels]
```

as can be seen when printing the corresponding types:

```
    print("type of si_level: %s" % type(si_level))
    print("type of prefix_levels: %s" % type(prefix_levels)) 
----
type of si_level: <class 'float'>
type of prefix_levels: <class 'float'>
```

To **fix** this issue both variables should be casted to int:

```
return prefix[(int)(si_level) + (int)(prefix_levels)]
```

**Comment by cfobel** [comment]
Thanks for letting me know about this.
