### ISSUE TITLE
Versioneer is not compatible with Python 3.12

### ISSUE THREAD

**Issue by LeonReinPMD** [cfobel/si-prefix#11]
The used Versioneer package uses SafeConfigParser, which was deprecated in Python 3.2 and removed in 3.12.

Please update to the newest version of Versioneer or remove it entirely to be compatible with Python 3.12.

**Comment by dechamps** [comment]
Seconded. For reference, here's an example error when attempting to pull `si-prefix` with Python 3.12:

```
Collecting si-prefix==1.2.2 (from videojitter)
  Downloading si-prefix-1.2.2.tar.gz (64 kB)
     ---------------------------------------- 64.9/64.9 kB ? eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      C:\Users\etien\AppData\Local\Temp\pip-install-s5_pges4\si-prefix_a5e1a90705c34c81b28d4b587ba49811\versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "C:\Users\etien\AppData\Local\pipx\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\etien\AppData\Local\pipx\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\etien\AppData\Local\pipx\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\etien\AppData\Local\Temp\pip-build-env-0nm0e61l\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\etien\AppData\Local\Temp\pip-build-env-0nm0e61l\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\etien\AppData\Local\Temp\pip-build-env-0nm0e61l\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\etien\AppData\Local\Temp\pip-build-env-0nm0e61l\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 11, in <module>
        File "C:\Users\etien\AppData\Local\Temp\pip-install-s5_pges4\si-prefix_a5e1a90705c34c81b28d4b587ba49811\versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "C:\Users\etien\AppData\Local\Temp\pip-install-s5_pges4\si-prefix_a5e1a90705c34c81b28d4b587ba49811\versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\etien\AppData\Local\Temp\pip-install-s5_pges4\si-prefix_a5e1a90705c34c81b28d4b587ba49811\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by dechamps** [comment]
Also for reference, the issue on the Versioneer side is python-versioneer/python-versioneer#375

**Comment by dechamps** [comment]
I took the liberty of sending a PR to upgrade versioneer in #12.

**Comment by Tomaubier** [comment]
Hi,
Any update on that? Is there any way to manually fix the issue ?
Best
Tom

**Comment by dechamps** [comment]
@Tomaubier For my project I ended up working around it by [vendoring si-prefix directly inside my code](https://github.com/dechamps/videojitter/commit/242db3677ccc5287bebd70e8ccaf179805cd9818) instead of depending on the pip package. This is fairly trivial to do since si-prefix is very small and does not have any dependencies.
